### PR TITLE
Shiny improvements

### LINKED ISSUE #6: Standardise function names
Given that a naming convention has begun naturally, I think we should retrospecitvely apply it to the other two functions:

E.g. 
- `PRISMA_flowdiagram()` (no change)

- `PRISMA_save()` (no change)

- `read_PRISMAdata()` -> `PRISMA_data()`

- `sr_flow_interactive()` -> `PRISMA_interactive()`

### LINKED ISSUE #9: Shiny improvements
The shinyapp version of this tool could benefit from some improvements:

- [x] replace "functions.R" with calls to the library version
- [x] add option within `PRISMA_flowchart()`to show, or hide, the blue side labels
- [x] add SVG download option
- [x] implement side labels to include text rotation
- [x] allow download of interactive HTML from shiny app

### PR DESCRIPTION
**Pull request by chriscpritchard**
This PR is for shiny improvements. Currently in a draft state as further improvements needed - this branch is based off the standard-functions branch, so #7 would ideally need to be merged before this.

Closes #6 
Closes #9

### CODE REVIEW

**Comment by chriscpritchard** [comment]
Tested this @nealhaddaway @mcguinlu works fine with the changes Neal made on the master branch so should be good to go and this can be released / deployed as V0.0.2 as it includes #7. I haven't tested on shinyapps.io as I don't have an account, but according to their website they support devtools::install_github() so it should just pull the latest version from here!

**Comment by nealhaddaway** [comment]
Great - thanks, Chris! And should I merge both PRs, or do one at a time...?

**Comment by chriscpritchard** [comment]
Just this one would be best as it includes the other one

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nealhaddaway** [comment]
Great - I've done that now

**Comment by nealhaddaway** [comment]
Hmm - it seems to have lost my code for removing blank lines in the sources boxes... But it's not super important...

**Comment by chriscpritchard** [comment]
THat's really annoying, give me a few minutes I'll try and see where that happened (might have been in the rejiggering of functions and I missed it when merging).

**Comment by chriscpritchard** [comment]
Yup I've found the issue, I think it was only updated in the shiny code so I missed it...

**Comment by nealhaddaway** [comment]
Ah cool - what's the best thing to do?

**Comment by chriscpritchard** [comment]
I'll fix it check it works and make a PR

**Comment by nealhaddaway** [comment]
Sweet - thank you!!
________________________________

**Comment by chriscpritchard** [comment]
Done, PR #12 fixes this, sorry I missed it. I've taken your code from the shiny function and added it to the main one

**Pull request merged**
