### PR TITLE
Support tibbles via coercion to data frame

### PR DESCRIPTION
**Pull request by chapb**
The use of `df[, 1]`, such as in `data[grep('previous_studies',3 data[,1]),]$n` is predicated on `[` returning a vector. If a tibble is passed to PRISMA_data(), grep() returns 1, and sets the first row's contents for all fields.

To support tibbles, `data` is coerced to a data frame.

### CODE REVIEW

**Comment by chriscpritchard** [comment]
Hi,

So sorry - life's got in the way and I haven't been able to test this. I hope to be able to do so in the next few weeks.

Chris

**Comment by chapb** [comment]
No rush! Happy holidays!

**Review by chriscpritchard — APPROVED** [review]

**Comment by chriscpritchard** [comment]
Hi,

Sorry this has taken so long! Would you like me to add you to our contributors file?

**Comment by chapb** [comment]
No problem! I'd be honoured to be added, but it was a pretty small fix - up to you!

**Pull request merged**
