### PR TITLE
Standardise function names

### LINKED ISSUE #6: Standardise function names
Given that a naming convention has begun naturally, I think we should retrospecitvely apply it to the other two functions:

E.g. 
- `PRISMA_flowdiagram()` (no change)

- `PRISMA_save()` (no change)

- `read_PRISMAdata()` -> `PRISMA_data()`

- `sr_flow_interactive()` -> `PRISMA_interactive()`

### PR DESCRIPTION
**Pull request by chriscpritchard**
Updated function names (mostly) as identified in #6. it seems that ```sr_flow_interactive()``` was better placed as an internal function, so I moved it to utils.R and renamed it to ```PRISMA_interactive_()```. Since I started with internal functions ending with an underscore, it makes sense to me that we continue with that naming scheme (although I'd be happy to consider another one too). I felt it was best to prefix them with PRISMA as well, so it's clear in the code what's an internal function and what's from elsewhere.

Additionally I added my ORCID and email address to the DESCRIPTION file.

Closes #6

### CODE REVIEW

**Comment by chriscpritchard** [comment]
I'm also wondering if this would be a good time to bump to version 0.0.2?

**Comment by chriscpritchard** [comment]
@mcguinlu @nealhaddaway would we be able to review / merge this soon?

**Comment by nealhaddaway** [comment]
I might need some help actually - I have some changes that I hadn't pushed to main yet that dropped lines with NA nicely if they were left empty. Should I push them all to the main before reviewing the pull request? @mcguinlu?

**Comment by chriscpritchard** [comment]
Assuming you've pushed them to Main, I'll rebase this branch, then rebase the other shiny-improvements branch as well

**Comment by nealhaddaway** [comment]
That sounds like magic, but I've just pushed them all - actually mostly the background files, but hopefully it doesn't cause problems...

**Comment by chriscpritchard** [comment]
> That sounds like magic, but I've just pushed them all - actually mostly the background files, but hopefully it doesn't cause problems...

No problem, I've rebased now so my branches are based off the latest commit to main. It's just a way of reducing merge conflicts and keeping the commit history clean.

**Comment by nealhaddaway** [comment]
Great thanks! So - I'm a REAL novice when it comes to GitHub. Do I need to review anything, or can I just merge? Does it all function as expected with my changes on your side?

**Comment by chriscpritchard** [comment]
I've not fully tested everything, but nothing I changed was touched per se. That said I'll have some time after 1600 today to properly test all functionality, once I've done that we could merge this and the shiny-updates branch (which I'll also check but depends on the commits from this) potentially tomorrow?

**Comment by nealhaddaway** [comment]
If that's OK with you, that would be amazing! I'm not savvy enough to be able to check anything, so I'd just have to merge and then check before deploying, so if you can check before I merge that sounds safer, right?

**Comment by chriscpritchard** [comment]
I closed this PR as I've tested the shiny-improvements PR which works fine with your changes and will encompass this PR

**Pull request closed without merging**
