### PR TITLE
assigns variables, removing need for attach()

### LINKED ISSUE #3: Remove need to attach() data
Hi @nealhaddaway, 

Prompted by a user I recommended the package to missing the `attach()` step and getting a non-informative error, it might be worth reassessing the need for users to `attach()` the data before they can run `PRISMA_flowchart()`. It would be better to explicitly refer to objects within the `PRISMA_flowchart()` function using `$` rather than the current set-up (e.g. so `tooltips` becomes `data$tooltips`). [**I imagine this is a hang-over from the old way the function inputs were defined, and is on the to-do list, but wanted to formally flag it** 😀]

Some more relevant info on why `attach()` can be dangerous here, in case it's useful: https://www.r-bloggers.com/2011/05/to-attach-or-not-attach-that-is-the-question/

### PR DESCRIPTION
**Pull request by chriscpritchard**
for loop loops through the dataset presented to PRISMA_flowdiagram and assigns to relevent variables, removing the need for attach()

fixes #3

### CODE REVIEW

**Comment by chriscpritchard** [comment]
This might still need a todo so that all the indiviudal variables can be changed to data$var but for now this makes the user experience better as no more cryptic errors

**Comment by nealhaddaway** [comment]
Can we close this PR now @chriscpritchard?

**Comment by chriscpritchard** [comment]
I think we still need to attach() unless you've changed anything? 

If not I can rebase and we can merge

**Comment by nealhaddaway** [comment]
Oh darn.. thought this was fixed, sorry!

Sent from my iPhone

On 7 Jul 2021, at 10:09, Chris Pritchard ***@***.***> wrote:

﻿

I think we still need to attach() unless you've changed anything?

If not I can rebase and we can merge

**Pull request closed without merging**
